version: "3"
services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
    restart: unless-stopped
    logging:
      driver: none

  api:
    container_name: express_api
    build:
      context: ./express-ws
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "4000:4000"
    depends_on:
      - mongo
    links:
      - mongo
    # for development hot reload
    #  volumes:
    #    - ./express-ws:/usr/src/app
    environment:
      - DATABASE=mongodb://mongo/test-db
      - PORT:5000
      - SOCKET_PORT:4000

  web:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-client
    environment:
      - REACT_APP_API=http://localhost:5000/api
      - REACT_APP_SOCKET=http://localhost:4000
    ports:
      - "3000:5000"
    depends_on:
      - api
