version: "3"
services:
  express_api:
    container_name: express_api
    build:
      context: ./express-ws
      dockerfile: Dockerfile
    networks: 
      - docker_default

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-client
    networks: 
      - docker_default
networks:
  docker_default:
    external: true
